In [61]:
import numpy as np
import array as ar

In [67]:
n_array=ar.array('i',[1,2,3,4]) # using array lib and definging type
n_array

array('i', [1, 2, 3, 4])

In [69]:
np_array=np.array([1,2,3,4],'int') #using numpy module datatype should be defined at the end
np_array

array([1, 2, 3, 4])

In [79]:
matri= np.matrix(np_array.reshape(2,2)) # matrix creation using matrix function
matri

matrix([[1, 2],
        [3, 4]])

In [65]:
numpy_array=np.arange(0,11,2) # if you pass only 11 it give values till 10
twodarray=numpy_array.reshape(3,2)
numpy_array
twodarray

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [22]:
twodarray.dtype

dtype('int64')

In [24]:
twodarray.shape

(3, 2)

In [26]:
twodarray.size

6

In [28]:
twodarray.ndim

2

In [40]:
zeros = np.zeros(shape=(5,5),dtype=int) #creating 5*5 zeroo array Directly we can mention (5,5) instead shape=(5,5)
zeros # default type is float 

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [42]:
ones = np.ones(shape=(5,5),dtype=int) #creating 5*5 ones array Directly we can mention (5,5) instead shape=(5,5)
ones # default type is float 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
arr_lin=np.linspace(1,5,10) # here 1 is staring index 5 is ending including 5 and 10 is devided into 10 pieces
arr_lin #equal distributions

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])