In [1]:
import numpy as np

In [5]:
arr=np.array([[1,2,3],[4,5,6]])

In [9]:
arr[0][2] #priting specific record 1st row 3rd record  General Syntax id arr[0,2]

3

In [11]:
arr[0,2]

3

In [13]:
arr[-1] # returns last row #if it is 1-D array we will get last record

array([4, 5, 6])

In [15]:
arr[1,2]=9 #changing the value

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 9]])

In [21]:
arr[1]=7 #changing entire Row

In [23]:
arr

array([[1, 2, 3],
       [7, 7, 7]])

In [25]:
arr[0]+2

array([3, 4, 5])