In [1]:
import numpy as np

In [28]:
my_arr=np.array([[1,2,3,4,5]],np.int8) #memory management np.int8 we can give 32 64 like this.
my_arr

array([[1, 2, 3, 4, 5]], dtype=int8)

In [32]:
my_arr[0,4] #Works in 2-D array #search array creation methods

5

In [36]:
zeros=np.zeros((4,6),dtype=int)
zeros

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [40]:
rangearr=np.arange(15)
rangearr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [42]:
lspace=np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [47]:
empty=np.empty((6,4)) #gives an empty array
empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
emptylike=np.empty_like(lspace) # It copies size from another array and amke an empty array
emptylike

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [53]:
ide=np.identity(45) #creates an 45 *45 metrixs
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [59]:
ide.size

2025

In [61]:
x=[[1,2,3],[4,5,6],[7,1,0]]
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
arr.sum(axis=0) #column sum

array([12,  8,  9])

In [67]:
arr.sum(axis=1) #row sum

array([ 6, 15,  8])

In [69]:
arr.T #it transposes rows into columns columns in rows

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [71]:
arr.flat # it works as iterator

In [73]:
for item in arr.flat: #we can print in sequence
    print(item)

1
2
3
4
5
6
7
1
0


In [79]:
arr.nbytes #returns bytes

72

In [81]:
one=np.array([1,2,3,4,5,65,34,23])
one

array([ 1,  2,  3,  4,  5, 65, 34, 23])

In [83]:
one.argmax() #returns max value index

5

In [85]:
one.argmin() #returns min value index

0

In [87]:
one.argsort() # returns the index values for how the values have to be in order sorting index numbers

array([0, 1, 2, 3, 4, 7, 6, 5])

In [89]:
arr.argmin()

8

In [91]:
arr.argmax()

6

In [93]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [97]:
arr.argmax(axis=0) #this returns least value index in each row o/p returns from last row first

array([2, 1, 1])

In [99]:
arr.argmin(axis=0) ##this returns least value index in each column o/p returns from first column first

array([0, 2, 2])

In [105]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [103]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [107]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [117]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [115]:
arr1=np.arange(9)
arr1=arr1.reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
arr+arr1

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13,  8,  8]])

In [119]:
np.sqrt(arr1)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [121]:
arr1.sum()

36

In [125]:
np.where(arr1>3)

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [127]:
np.count_nonzero(arr1) #count of non zeros

8

In [131]:
np.nonzero(arr1) #returns nonzero insex values first list is rows and secod in column

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))

In [133]:
import sys

In [135]:
lst=[45,24,55,67] #below is to check space occupied by normal list and numpy array

In [137]:
num_lst=np.array(lst)

In [139]:
sys.getsizeof(1)*len(lst)

112

In [141]:
num_lst.itemsize*num_lst.size

32

In [143]:
num_lst.tolist() #converts numpy array to python list

[45, 24, 55, 67]