In [2]:
import numpy as np

In [35]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
reshaped=arr.reshape(3,4)
reshaped

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
flattened=reshaped.flatten() # to make it as 1-D array
flattened[0]=99 # IT IS COPING FROM ORIGINAL ,original will not change when we change in flattened
flattened

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
raveled=reshaped.ravel() #to make it as 1-D array
raveled[0]=99 # it like a view of original when we change in raveled it will effect in original
raveled

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#flatten - Copy
#ravel() - View